# Generated by Django 2.2.6 on 2019-10-11 09:22

import astrosat_users.models
import core.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A pretty display name for the bookmark', max_length=128)),
                ('zoom', models.FloatField(help_text='The zoom level of the bookmark on the map.')),
                ('center', django.contrib.gis.db.models.fields.PointField(help_text='The center point of this bookmark on the map', srid=4326)),
                ('feature_collection', django.contrib.postgres.fields.jsonb.JSONField(help_text='a GeoJSON description of the data being bookmarked.', validators=[core.models.validate_feature_collection])),
                ('owner', models.ForeignKey(on_delete=models.SET(astrosat_users.models.get_deleted_user), related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'title')},
            },
        ),
    ]
